[project]
name = "digital-marketing"
version = "1.0.0-SNAPSHOT"
description = "Digital marketing platform for influencers that can significantly optimize campaigns, streamline processes, and drive better results"
authors = [{ name = "Zack4DEV", email = "73597675+Zack4DEV@users.noreply.github.com" }]
license = { text = "MIT-License" }
readme = "README.md"
requires-python = "^3.8"
keywords = ["digital", "marketing", "ai", "llm"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
repository = "https://github.com/Zack4DEV/streamLit--Digital-Marketing"
homepage = "https://digital-marketing.streamlit.app/"

[tool.poetry]
name = "digital-marketing"
version = "1.0.0-SNAPSHOT"
description = "Digital marketing platform for influencers that can significantly optimize campaigns, streamline processes, and drive better results"
authors = ["Zack4DEV <73597675+Zack4DEV@users.noreply.github.com.>"]
license = "MIT-License"
readme = "README.md"
packages = [{include = "./*", from = "."}]
repository = "https://github.com/Zack4DEV/streamLit--Digital-Marketing"
homepage = "https://digital-marketing.streamlit.app/"
keywords = ["digital","marketing" ,"ai", "llm"]
requires-python = ">=3.8"

[tool.poetry.dependencies]
python = ">=3.8"
streamlit = "^1.25.0" 
openai = "^1.77.0"
requests = "^2.32.3"
mendable-py = "^0.0.6"
pandas = "^2.2.3"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core^1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
streamlit_app = "streamlit run streamlit_app.py" # to run streamlit app from poetry

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
