name: Docker Hub ,Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v3
      
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            
          - name: "Digital Marketing ,Docker Hub Build and Push"
            uses: mr-smithers-excellent/docker-build-push@v6.4
            with:
              dockerfile: ./Docker/3.13-slim/Dockerfile
              registry: remote
              username: ${{ secrets.HUB_DOCKER_USERNAME }}
              password: ${{ secrets.HUB_DOCKER_PASSWORD }}
              tags: local/digital-marketing:latest
              platforms: linux/amd64, linux/arm64
              pushImage: false