name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: [ 'upstream' ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Web
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Checkout code
        uses: actions/checkout@v3

      - name: ⚙ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🌐 Build Expo Web
        run: npx expo export --platform web

      - name: 🚀 Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
            preview: true